### ISSUE TITLE
Retrofit extension installation procedure for non maven users

### ISSUE THREAD

**Issue by homer123** [octo-technology/RoboSpice-samples#10]
Hi
What is the procedure to install the retrofit extension. I am a non maven user. I have the retrofit jar in the lib folder. But I am not sure how to add the retrofit related files from the extension folder. I can contribute to the documentation if someone can provide a procedure. I will add it to the wiki.

**Comment by stephanenicolas** [comment]
Hi @homer123 ,

you can find all the jars needed inside this folder : https://github.com/octo-online/robospice/tree/repository/dependencies/1.4.6-SNAPSHOT/robospice-retrofit

If you compare it to a different set up guide for another lib, you can quickly write the documentation. We would be glad if you could contribute to it. Copy-paste as much as you want, re-read and that's fine for us.

Thx in advance,
 Stéphane

**Comment by homer123** [comment]
Hi
I tried to edit the wiki but it said I dont have permission. 

The problem I faced was that one has to change to the repository branch to see all the jars needed for the extension. I kept looking for it on the release branch. Hence a small note on the main page providing the link to the jars for the extension module would help.

Thank you for the quick reply.

**Comment by stephanenicolas** [comment]
Hi homer123,

the wiki is not public, but you can issue a pull request very easily
through github. All edit buttons will create a fork, then you can edit your
fork, then submit the pull request. The process is as simple as a click for
you.

Stéphane

2013/7/18 homer123 notifications@github.com

> Hi
> I tried to edit the wiki but it said I dont have permission.
> 
> The problem I faced was that one has to change to the repository branch to
> see all the jars needed for the extension. I kept looking for it on the
> release branch. Hence a small note on the main page providing the link to
> the jars for the extension module would help.
> 
> Thank you for the quick reply.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/octo-online/RoboSpice-samples/issues/10#issuecomment-21153522
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - blog.octo.com
www.usievents.com
...........................................................
