### ISSUE TITLE
zhe sample of robospice-sample-google-http-client has stoped when running！

### ISSUE THREAD

**Issue by JustBugFarmer** [octo-technology/RoboSpice-samples#12]
10-16 03:39:31.602: E/AndroidRuntime(5369): java.lang.NoClassDefFoundError: org.codehaus.jackson.JsonFactory
10-16 03:39:31.602: E/AndroidRuntime(5369):     at com.google.api.client.json.jackson.JacksonFactory.<init>(JacksonFactory.java:44)
10-16 03:39:31.602: E/AndroidRuntime(5369):     at com.octo.android.robospice.persistence.googlehttpclient.json.JacksonObjectPersisterFactory.<init>(JacksonObjectPersisterFactory.java:33)
10-16 03:39:31.602: E/AndroidRuntime(5369):     at com.octo.android.robospice.sample.googlehttpclient.SampleSpiceService.createCacheManager(SampleSpiceService.java:21)

**Comment by stephanenicolas** [comment]
You are right : this dependency seems to be missing in the sample 

``` xml
<groupId>com.google.http-client</groupId>
<artifactId>google-http-client-jackson</artifactId>
<version>x.y.z</version>
```
