### ISSUE TITLE
Unable to do "mvn clean install -Pant" for  Robospice motivation project.

### ISSUE THREAD

**Issue by nilkashid** [octo-technology/RoboSpice-samples#4]
Hi I am just trying to learn and integrate Robospice library for my android project. I build few project successfully. But I am not able build few of sample. like in my robospice  motivation project when i tried to do "mvn clean install -Pant" it gives me following error 

[INFO] /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/target/unpack/apklibs/com.actionbarsherlock_actionbarsherlock_apklib_4.2.0/res/values-v14/abs__themes.xml:32: error: Error retrieving parent for item: No resource found that matches the given name 'android:Theme.Holo.Light.Dialog'.
[ERROR] Error when generating sources.
org.apache.maven.plugin.MojoExecutionException: 

[ERROR] Failed to execute goal com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.4.2-SNAPSHOT:generate-sources (default-generate-sources) on project robospice-motivations: MojoExecutionException: ANDROID-040-001: Could not execute: Command = /bin/sh -c cd /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations && /home/nilkash/Downloads/android-sdk-linux/platform-tools/aapt package -m -J /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/target/generated-sources/r -M /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/AndroidManifest.xml -S /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/res -S /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/target/unpack/apklibs/com.actionbarsherlock_actionbarsherlock_apklib_4.2.0/res --auto-add-overlay -A /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/assets -I /home/nilkash/Downloads/android-sdk-linux/platforms/android-7/android.jar, Result = 1 -> [Help 1]

I dot know how to solve this problem according to this I did some few changes but its not working. Need help thank you ....

**Comment by stephanenicolas** [comment]
Hi Nilkash,

RoboSpice motivations is a bit part and can't really be counted as a
sample. It's a pedagogical app that we use as a demonstrator with lots of
explanations to demonstrate why RoboSpice is better than AsyncTasks and
Loaders when it comes to networking.
It relies on some libraries, such as ActionBarSherlock and might be
difficult to setup.

Nevertheless, what really matters to developers are all the other samples.
You just picked the wrong one.

Stéphane

2013/3/4 nilkashid notifications@github.com

> Hi I am just trying to learn and integrate Robospice library for my
> android project. I build few project successfully. But I am not able build
> few of sample. like in my robospice motivation project when i tried to do
> "mvn clean install -Pant" it gives me following error
> 
> [INFO]
> /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/target/unpack/apklibs/com.actionbarsherlock_actionbarsherlock_apklib_4.2.0/res/values-v14/abs__themes.xml:32:
> error: Error retrieving parent for item: No resource found that matches the
> given name 'android:Theme.Holo.Light.Dialog'.
> [ERROR] Error when generating sources.
> org.apache.maven.plugin.MojoExecutionException:
> 
> [ERROR] Failed to execute goal
> com.jayway.maven.plugins.android.generation2:android-maven-plugin:3.4.2-SNAPSHOT:generate-sources
> (default-generate-sources) on project robospice-motivations:
> MojoExecutionException: ANDROID-040-001: Could not execute: Command =
> /bin/sh -c cd
> /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations
> && /home/nilkash/Downloads/android-sdk-linux/platform-tools/aapt package -m
> -J
> /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/target/generated-sources/r
> -M
> /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/AndroidManifest.xml
> -S
> /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/res
> -S
> /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-motivations/target/unpack/apklibs/com.actionbarsherlock_actionbarsherlock_apklib_4.2.0/res
> --auto-add-overlay -A
> /home/nilkash/Desktop/robospice_sample/RoboSpice-samples/robospice-mot
> ivations/assets -I
> /home/nilkash/Downloads/android-sdk-linux/platforms/android-7/android.jar,
> Result = 1 -> [Help 1]
> 
> I dot know how to solve this problem according to this I did some few
> changes but its not working. Need help thank you ....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/octo-online/RoboSpice-samples/issues/4
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - blog.octo.com
www.usievents.com
...........................................................

**Comment by StingerAJ** [comment]
The important bit here seems to be:  "No resource found that matches the given name 'android:Theme.Holo.Light.Dialog'."

... which for me points to the correct Android SDK platform containing Theme.Holo.Light.Dialog (android-16) not being installed with the SDK manager. Could that be the issue here?

**Comment by nilkashid** [comment]
I build with android-16 but still giving same problem. I don't know why. Whether this is because of ActionBarSherlock or because of some thing else? Thank you for help..

**Comment by stephanenicolas** [comment]
All of this comes from ABS I believe. There is a special lint file that you
should use when checking the ABS-based project with lint.
You can find this file on stack over flow.

S.

2013/3/11 nilkashid notifications@github.com

> I build with android-16 but still giving same problem. I don't know why.
> Whether this is because of ActionBarSherlock or because of some thing else?
> Thank you for help..
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/octo-online/RoboSpice-samples/issues/4#issuecomment-14708737
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - blog.octo.com
www.usievents.com
...........................................................
