### ISSUE TITLE
Samples are outdated

### ISSUE THREAD

**Issue by onyxmueller** [octo-technology/RoboSpice-samples#8]
The RoboSpice samples are outdated. For example, the Retrofit sample is 6 months old. The version of the RoboSpice library that was used to create the sample (1.3.x?) no longer matches the current architecture (1.4.4).

**Comment by onyxmueller** [comment]
For anyone else looking, I found updated samples on the master branch.

https://github.com/octo-online/RoboSpice-samples/tree/master/robospice-sample-retrofit

**Comment by Shusshu** [comment]
Also the Twitter API has changed and the previous one has been taken down

**Comment by rciovati** [comment]
@Shusshu we are incrementally migrating our samples from Twitter APIs to Github.

**Comment by stephanenicolas** [comment]
And any help is welcome :)

2013/7/2 Riccardo Ciovati notifications@github.com

> @Shusshu https://github.com/Shusshu we are incrementally migrating our
> samples from Twitter APIs to Github.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/octo-online/RoboSpice-samples/issues/8#issuecomment-20359177
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - blog.octo.com
www.usievents.com
...........................................................

**Comment by Shusshu** [comment]
I can help you for twitter but you need to request a API key from twitter
and I can give your the requests for that

Benoit Billington

**Comment by stephanenicolas** [comment]
I personally prefer using github as its free and merely the source of all
things we enjoy as oss devs. ;)

S.
Le 12 juil. 2013 18:48, "Benoit Billington" notifications@github.com a
écrit :

> I can help you for twitter but you need to request a API key from twitter
> and I can give your the requests for that
> 
> Benoit Billington
> 
> On Fri, Jul 12, 2013 at 1:24 AM, stephanenicolas

**Comment by stephanenicolas** [comment]
All samples have been migrated to GitHub. We still need to check if they have been updated to last RS version. When so, close that thread.
