### ISSUE TITLE
Migrate samples to Gradle

### ISSUE THREAD

**Issue by rciovati** [octo-technology/RoboSpice-samples#9]
With the commit 13a42ed3528e8e3b3734d63d05ecd780a70222ce I started migrating our samples to Gradle so it would be easier to use RS for users who don't use Maven.

I would skip the whole part of converting samples to ant since it has been deprecated (or it will be very soon).

What I did so far:
- Converting the folder structure to the new one
- Creating the `build.gradle` file for each sample 

What should be done:
- [x] Fix the `robospice-sample-motivation` since it uses `ActionBarSherlock` and it is not available yet as `aar`. 
- [ ] Fix the `robospice-sample-ormlite-content-provider` since it uses the `com.tojc.ormlite.android:ormlite-content-provider-compiler`which has a `provided` scope. I made a few attempts to get it working but I failed. If someone have an idea please share. 
- [ ] Test a little bit if it is working properly.

**Comment by stephanenicolas** [comment]
We should also provide some documentation for it.

**Comment by rciovati** [comment]
Updated gradle version and fixed motivation app.

**Comment by stephanenicolas** [comment]
Nice ! :)

2013/9/14 Riccardo Ciovati notifications@github.com

> Updated gradle version and fixed motivation app.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/octo-online/RoboSpice-samples/issues/9#issuecomment-24439242
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................
